:toc:

A Kubernetes operator for proxying HTTP services. Create a simple service quickly that proxies 1 or more other services, and control the traffic with an HTTP header.  You can deploy it to Kubernetes with just a few lines of YAML:

```
apiVersion: spring.io/v1
kind: ProxyService
metadata:
  name: demo
spec:
  services:
  - green
  - blue
```

The result of applying this YAML is to replace the first `Service` (i.e. "green" in this example) with one that forwards HTTP requests to the existing services ("green" and "blue", which must exist). So set up a port forward:

```
$ kubectl port-forward svc/green 8080:80
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
```

and then in another terminal

```
$ curl localhost:8080 -H "X-Server-Select: blue"
Blue
$ curl localhost:8080 -H "X-Server-Select: green"
Green
$ curl localhost:8080
Green
```

Requests go to the first service listed by default, and can be sent to other services by adding an HTTP header `X-Server-Select` equal to the service name. Routing by a cookie is also supported:

```
$ curl localhost:8080 -H "Cookie: backend=blue"
Blue
$ curl localhost:8080 -H "Cookie: backend=green"
Green
$ curl localhost:8080
Green
```

The responses have headers that record the routing decision:

```
$ curl -v localhost:8080 -H "Cookie: backend=blue"
...
< X-Server: blue
< X-Route: cookies
...
```

In a browser there is an endpoint you can visit `/choose/{route}` to set the cookie.

When you delete the `ProxyService` the original service is re-instated. The proxy is implemented with nginx so it's pretty lightweight.

== Installation

The controller is in Dockerhub, so you should be able to deploy it from just the YAML:

```
$ kubectl apply -f <(kustomize build github.com/dsyer/spring-service-operator/config/default)
```

One `Service` for the controller is installed into the `spring-system` namespace:

```
$ kubectl get all -n spring-system
NAME                                             READY   STATUS    RESTARTS   AGE
pod/spring-controller-manager-79c6c95677-8hf89   2/2     Running   0          3m17s

NAME                                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/spring-controller-manager-metrics-service   ClusterIP   10.111.94.226   <none>        8443/TCP   3m17s

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/spring-controller-manager   1/1     1            1           3m17s

NAME                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/spring-controller-manager-79c6c95677   1         1         1       3m17s
```

```
$ kubectl delete proxyservices --all
$ kubectl delete namespace spring-system
```

=== Building from Source

If you know how to set up a GO lang development environment, and are building from source you can just do this:

```
$ make install
$ make run
```

and then the controller will register with your default cluster.

[TIP]
====
You may encounter issues with go modules. If you see this:

```
# sigs.k8s.io/controller-tools/pkg/webhook
/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:98:29: undefined: v1beta1.Webhook
/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:129:9: undefined: v1beta1.Webhook
/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:161:21: undefined: v1beta1.Webhook
/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:162:23: undefined: v1beta1.Webhook
make: *** [Makefile:69: controller-gen] Error 2
```

try this:

```
$ (cd .. && GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.1)
$ make install run
```
====

The source code has a VSCode `.devcontainer` definition, so if you use the "Remote Container" extension, you should be able to run in a container. The `devcontainer.json` has comments explaining what to set up on the host (you need to have `docker` running and set up your `~/.kube/config` to talk to your cluster).
